export type AITaskType =
  | "content_generation"
  | "checker"
  | "lesson_planning"
  | "study_materials"
  | "rubric_generation"
  | "paper_generation"
  | "worksheet_generation"
  | "quiz_questions"
  | "differentiation"
  | "concept_explanation"
  | "practice_questions"
  | "flashcards"
  | "study_plan"
  | "contract_generation"
  | "contract_revision"
  | "teacher_test_generation"
  | "teacher_evaluation"
  | "tutor_matching"
  /** Owner-run AI gateway health check; one credit per run regardless of model count. */
  | "model_test";
